export const booksData = [
    {
      id: 1,
      imgUrl:"https://hachette.imgix.net/books/9780762498130.jpg?auto=compress&w=440",
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      genre: "Classic",
      rating: 4.7,
      description: "A novel set in the Jazz Age that explores themes of wealth, love, and the American Dream.",
      publication_year: 1925,
    },
    {
      id: 2,
      imgUrl:"https://cdn2.penguin.com.au/covers/original/9781785150357.jpg",
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      genre: "Fiction",
      rating: 4.8,
      description: "A timeless novel of a child's moral awakening and a poignant tale of race and justice in the American South.",
      publication_year: 1960,
    },
    {
      id: 3,
      imgUrl:"https://www.designer-daily.com/wp-content/uploads/2017/02/1984-book-covers-6.jpg",
      title: "1984",
      author: "George Orwell",
      genre: "Dystopian",
      rating: 4.6,
      description: "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism.",
      publication_year: 1949,
    },
    {
      id: 4,
      imgUrl:"https://cdn2.penguin.com.au/covers/400/9780141330167.jpg",
      title: "Pride and Prejudice",
      author: "Jane Austen",
      genre: "Romance",
      rating: 4.9,
      description: "A romantic novel that also serves as a social commentary on the British landed gentry of the early 19th century.",
      publication_year: 1813,
    },
    {
      id: 5,
      imgUrl:"https://www.bookishelf.com/wp-content/uploads/2020/01/Book-Review-The-Catcher-in-the-Rye-by-J-D-Salinger-768x1269.jpg",
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      genre: "Fiction",
      rating: 4.3,
      description: "A story about a young boy’s journey through the challenges of adolescence.",
      publication_year: 1951,
    },
  ];
  